// <auto-generated />
using ContactListWebService.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactListWebService.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20221014134216_UserDbInitial")]
    partial class UserDbInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("ContactListWebService.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subcategory")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = 0,
                            Subcategory = "",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = 1,
                            Subcategory = "",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = 2,
                            Subcategory = "Other than other",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ContactListWebService.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BirthDate = "1990-12-1",
                            Email = "smith@onet.pl",
                            Name = "Wilson",
                            Password = "CfDJ8NexdWr8pwVLtd6Bq9KrAxHnB1yxocpHLyp58_sYx6SnpDu5-h13HgDtfA4TXvO_5YesDkq1i9KvOIu6sxNgQwW4jpPjClzPKt_0ayP8-LMzmjAe9mlhP7AIZMEQo9TSWg",
                            Phone = "504-555-555",
                            Surname = "Smith"
                        },
                        new
                        {
                            UserId = 2,
                            BirthDate = "2001-12-1",
                            Email = "jk@poczta.com",
                            Name = "Adam",
                            Password = "CfDJ8NexdWr8pwVLtd6Bq9KrAxHnB1yxocpHLyp58_sYx6SnpDu5-h13HgDtfA4TXvO_5YesDkq1i9KvOIu6sxNgQwW4jpPjClzPKt_0ayP8-LMzmjAe9mlhP7AIZMEQo9TSWg",
                            Phone = "888-334-333",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            UserId = 3,
                            BirthDate = "2020-01-1",
                            Email = "jn2000@gmail.com",
                            Name = "Jan",
                            Password = "CfDJ8NexdWr8pwVLtd6Bq9KrAxHnB1yxocpHLyp58_sYx6SnpDu5-h13HgDtfA4TXvO_5YesDkq1i9KvOIu6sxNgQwW4jpPjClzPKt_0ayP8-LMzmjAe9mlhP7AIZMEQo9TSWg",
                            Phone = "111-444-333",
                            Surname = "Niezbedny"
                        });
                });

            modelBuilder.Entity("ContactListWebService.Entities.Category", b =>
                {
                    b.HasOne("ContactListWebService.Entities.User", "User")
                        .WithOne("UserCategory")
                        .HasForeignKey("ContactListWebService.Entities.Category", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContactListWebService.Entities.User", b =>
                {
                    b.Navigation("UserCategory")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
